import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BG from "@/components/bg";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* <Script
          type="text/javascript"
          src="//pl26702585.profitableratecpm.com/07/5c/3d/075c3ded807656e7ab17f0a998d9d131.js"
        ></Script> */}
        <meta
          name="8aee87e0941ed401ec6dcbd041ba46ac9b381396"
          content="8aee87e0941ed401ec6dcbd041ba46ac9b381396"
        />
        <meta name="referrer" content="no-referrer-when-downgrade" />
        <Script type="text/javascript" src="/add.js"></Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BG>{children}</BG>
      </body>
    </html>
  );
}
